language: node_js
node_js:
  - 12

before_install:
  - cd webapp
  - npm ci
  - npm i -g npm@6.14.5

script:
  - npm run build
  - npm test
#  - npm run start:ci &
#  - npm run cy:run -- --record --parallel

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: webapp/dist/
  on:
    branch: master
