language: node_js

before_install:
  - cd webapp
  - npm i -g npm@6.14.5

script:
  - npm run build
  - npm test

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: webapp/dist/
  on:
    branch: master
