export const SETTINGS_RESET = 'SETTINGS_RESET'
export const SET_SETTINGS_CLOCK = 'SET_SETTINGS_CLOCK'
export const SET_SETTINGS_LANGUAGE = 'SET_SETTINGS_LANGUAGE'
export const SET_SETTINGS_USERNAME = 'SET_SETTINGS_USERNAME'
export const SET_SETTINGS_THEME = 'SET_SETTINGS_THEME'
export const SET_SETTINGS_SENDTYPE = 'SET_SETTINGS_SENDTYPE'

export const SEND_MESSAGE = 'SEND_MESSAGE'
export const UPDATE_MESSAGES_LIST = 'UPDATE_MESSAGES_LIST'
