export const SET_ROUTE = 'SET_ROUTE'

export const SETTINGS_RESET = 'SETTINGS_RESET'
export const SET_SETTINGS_HOURFORMAT = 'SET_SETTINGS_HOURFORMAT'
export const SET_SETTINGS_LANGUAGE = 'SET_SETTINGS_LANGUAGE'
export const SET_SETTINGS_USERNAME = 'SET_SETTINGS_USERNAME'
export const SET_SETTINGS_THEME = 'SET_SETTINGS_THEME'
export const SET_SETTINGS_SENDTYPE = 'SET_SETTINGS_SENDTYPE'

export const SET_CHAT_MESSAGE = 'SET_CHAT_MESSAGE'
export const ADD_CHAT_MESSAGE = 'ADD_CHAT_MESSAGE'
export const RECEIVE_CHAT_MESSAGE = 'RECEIVE_CHAT_MESSAGE'

export const ADD_UNREAD_MESSAGE = 'ADD_UNREAD_MESSAGE'
export const CLEAR_UNREAD_MESSAGES = 'CLEAR_UNREAD_MESSAGES'
